<?php

namespace Jr\Bundle\ExempleAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExempleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExempleRepository extends EntityRepository
{
}
